package com.sbcc.rules;

import com.sbcc.businessrules.model.CaseEvent;
import com.sbcc.businessrules.model.CaseAction;
import com.sbcc.businessrules.model.MilestoneAction;
import com.sbcc.businessrules.model.ActivityAction
import com.sbcc.businessrules.model.types.MilestoneActionEnum
import com.sbcc.businessrules.model.types.ActivityActionEnum;
import com.sbcc.businessrules.model.types.CaseEventTypeEnum;

global com.sbcc.businessrules.model.CaseAction caseAction;
dialect "mvel"

rule "Activity Action"
	when
		caseEvent:CaseEvent(eventType==CaseEventTypeEnum.ACTIVITY_EVENT)
	then
	    ActivityAction activityAction = new ActivityAction();
        activityAction.setActivityName(caseEvent.getActivityEvent().getActivityName());
        activityAction.setAction(ActivityActionEnum.ACTIVATE);
		caseAction.setActivityAction(activityAction);
	end

rule "Milestone Action"
	when
		caseEvent:CaseEvent(eventType==CaseEventTypeEnum.MILESTONE_EVENT)
	then
        MilestoneAction milestoneAction = new MilestoneAction();
        milestoneAction.setMilestoneName(caseEvent.getMilestoneEvent().getMilestone());
        milestoneAction.setAction(MilestoneActionEnum.REACH);
        caseAction.setMilestoneAction(milestoneAction);
	end
